package core

// **************************************
// AUTO GENERATED BY BASE_STATS_PARSER.PY
// **************************************

const ExpertisePerQuarterPercentReduction = 2.500000

// Crit/Hit/Haste ratings are straight percentage values in classic
// TODO: Update Defense/Dodge/Parry rates
const CritRatingPerCritChance = 1
const SpellCritRatingPerCritChance = 1
const MeleeHitRatingPerHitChance = 1
const SpellHitRatingPerHitChance = 1
const ExpertiseRatingPerExpertiseChance = 1
const DefenseRatingPerDefense = 1
const DodgeRatingPerDodgeChance = 1
const ParryRatingPerParryChance = 1
const BlockRatingPerBlockChance = 1
const ResilienceRatingPerCritReductionChance = 28.750002
